version: '3.7'



services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: task-manager-backend
    ports:
      - '4000:3000'
    # volumes:
      # - ./backend:/app
      # - /app/node_modules
    restart: 'unless-stopped'
    networks:
      - backend
    links:
      - mongo
    depends_on:
      - mongo

  mongo:
    image: mongo:5.0
    container_name: mongodb
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    networks:
      - backend

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: task-manager-frontend
    ports:
      - '3000:80' # Expose Nginx on host:container
    restart: unless-stopped
    networks:
      - backend
    depends_on:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  mongo-data: